### ISSUE TITLE
Question: Can i reinstall OS

### ISSUE THREAD

**Issue by Shashwatsh** [Feathur/Feathur#121]
Hi can i reinstall OS of a VPS? what does rebuild command do?

**Comment by danielisaksen** [comment]
Rebuild is for reinstalling a VPS.

- Daniel

**Comment by Shashwatsh** [comment]
reinstalling a VPS (as in reinstalling OS of a VPS)? if so then where is the code that does that? I'm trying to contribute to the rebuild of this project

**Comment by NerdGuruDevelopers** [comment]
Here would be a good place to start looking:

https://github.com/Feathur/Feathur/blob/Testing/feathur/includes/functions/vps.openvz.class.php#L543

Sorry for not replying sooner for whatever reason I didn't get a notification about the issue.
